---
title: "Problem set 8"
subtitle: "PPHA 32300 Microeconomics and Public Policy I"
author: "Jay Ballesteros"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---
# Part II

## Q1

**1.a. For Jasmine, what is the marginal utility of consumption? What is the marginal utility of leisure?**

$$MU_c=h-80$$

$$MU_h = c-200$$


**1.b. Derive Jasmine’s budget set, and graph it. Put consumption (in dollars) c on y-axis,and hours spent at home (i.e. leisure) h on x-axis. Also indicate the c-intercept, h-intercept, and the kink on the graph.**

Given that $L = 168-h$ and post-tax wage 10.2,

$$10.2(168-h) + 270$$
$$10.2(178)=1713.6$$

So,
$$c=1713.6-10.2h+270=1983.6-10.2h$$

**1.c. Solve for the tangency condition at optimal bundle (c , h). (Hint: The answer should be expressed as c = ah + b. What are the values of a and b?)**

$$MRS_{h,c}=\frac{c-200}{h-80}=10.2$$

$$c-200=10.2(h-80)$$
$$c=10.2h-10.2(80)+200=10.2h-616$$

So

$$a=10.2$$
$$b=-616$$

**1.d. Based on the results in the previous questions, solve for Jasmine’s optimal bundle of consumption and leisure. In each case, you may round to the nearest dollar or hour, respectively. How many hours a week does she work?**

$$1983.6-10.2h=10.2h-616$$
$$1983.6+616=20.4h$$

$$2599.6=20.4h$$

$$h=\frac{2599.6}{20.4}=127.43$$

So for hours of work:

$$L=168-h=168-127.43=40.57$$

and consumption:

$$c=10.2h-616=683.8$$


**1.e. Given these changes to her wages and non-labor income, find the new budget constraint and tangency condition.**

Given the new tax, the new budget is:

$$c=10.8(168-h)+230$$
$$10.8(168)=1814.4$$
$$c=1814.4-10.8h+230=2044.4-10.8h$$

And for the tangency condition,

$$\frac{c-200}{h-80}$$
$$c-200=10.8(h-80)$$
$$c=10.8h-10.8(80)+200=10.8h-664$$


**1.f. Solve for Jasmine’s new optimal bundle of consumption and leisure. You may round to the nearest dollar or hour, respectively. How many hours a week does she work? What is her new consumption level?**

$$2044.4-10.8h=10.8h-664$$
$$2044.4+664=21.6h$$
$$2708.4=21.6h$$

$$h=\frac{2708.4}{21.6}=125.39$$

Hours of work:
$$L=168-h=42.61$$

Consumption:
$$c=10.8h-664=690.2$$

**1.g. Is Jasmine better off or worse off under the OBBB? Provide a brief analysis of how it affected her. You may assume that both consumption and leisure are normal goods. (Hint: Use her utility function to rank the pre- and post-OBBB bundles.)**

For the old utility,

$$U_old=(c-200)(h-80)=(683.8-200)(127.43-80)=483.8\times47.43=22947.3$$

For the new(post-OBBB),

$$U_new=(c-200)(h-80)=(690.2-200)(125.39-80)=490.2\times45.39=22249.6$$

Given that the new utility is less that the old one, Jasmine is worse off under the OBBB.

## Q2

**2.a Write down Bruno’s budget constraint, in terms of consumption (cB) and time at home (hB) and a wage w.**

Bruno has 112 hours per week, time at home $h_B$, hours worked $L_B = 112 - h_B$, wage $w$, no non-labor income:

$$cB =wLB =w(112-hB)$$

**2.b. Derive Bruno’s labor supply function LB(w). Suppose that Bruno is paid a wage of w = 30 per hour. How many hours will he work?**

Given the utility,

$$U(cB,hB)=cB+1500ln(hB)$$

$$U(hB)=w(112-hB)+1500ln(hB)$$

**2.c. Charlie is also a musician. Like Bruno, he has 112 hours per week to spend on either time at home or working. Charlie does receive a pension of $300 per week, no matter how much he works. Write down Charlie’s budget constraint as a relationship between consumption (cC), time at home (hC), his wage w, and his non-labor income (YC = 300).**

Charlie has 112 hours, time at home $h_C$, hours worked $L_C = 112 - h_C$, wage $w$, non-labor income $Y_C = 300$:

$$cC=wLC+YC=w(112-hC)+YC$$

**2.d. Suppose Charlie has preferences over time at home (hC) and consumption (cC) represented by the following utility function: U(cC, hC) = cC × hC How many hours will Charlie work at a wage of w = 20?**

Given $w=20$ and $Yc=300$
$$hC=2(20)112(20)+300=402240+300=402540=63.5$$

Hours of work:
$$LC=112-hC=112-63.5=48.5$$

**2.e. As a result of a copyright settlement, Bruno must pay one-third of his earnings to Charlie. Bruno keeps the rest. Write down Bruno’s new budget constraint, in terms of time at home (hB) and consumption (cB) and his wage w.**

Since Bruno is keeping two thirds, his consumption is:
$$C_B=\frac{2}{3}w(112-h_B)$$
$$C_B+\frac{2}{3}wh_B=\frac{2}{3}\times112$$


**2.f. Suppose Bruno’s wage is still w = 30. Show that his settlement payment to Charlie will be $370.**

So Bruno's wage in this scenario, 

$$w=\frac{2}{3}(30)=20$$

Now considering Bruno’s labor supply with wage,

$$h_B=\frac{1500}{20}=75$$
$$L_B=112-75=37$$

So the payment,

$$\frac{1}{3}(30\times37)=10\times37=370$$

**2.g. After the settlement, what is Charlie’s new budget constraint in terms of consumption (cC) and time at home (hC), his wage w, and non-labor income (YC = 300) and his settlement payment?**

**2.h. What will be Charlie’s new level of labor supply after the copyright settlement? Charlie’s wage is still w = 20.**

**2.i. (i) (0 points) Define the income elasticity of labor supply as (some equation). Calculate Charlie’s income elasticity of labor supply.**





