#!/usr/bin/python
#
# Palmer LTER - Weather Processing Scripts
# Monthly averaged weather: knb-lter-pal.189
#
# This script calculates the monthly average weather for Palmer Station, Antarctica,
# based on a merged version of the daily weather (climatology) dataset (knb-lter-pal.28).
#
# The daily climatology data files are generated by the Palmer Station RA's, and made
# available by the by the ARMC archive at UW-Madison.  Daily averages have been
# calculated a variety of ways over the years, including high/low measurements
# in the 80's, to 4x daily measurements in the 90's, and then averages of 1-2 minute
# data after Nov. 2001.  Instrumentation has also changed over that time, from manual
# to automatic.  Thus, care must be taken when interpreting monthly averages.
#
# Edited by Sage Lichtenwalner, Rutgers University, 9/1/2023


# Primary function
def main():
  df = pd.read_csv('PalmerStation_Daily_Weather.csv', index_col='Date', parse_dates=True)
  
  # Fix Precipitation - Version 8 considered Trace to be NaN.  In version 9, let's make them 0.
  df['Precipitation Melted (mm)'] = df['Precipitation Melted (mm)'].replace('T', 0)  # Change to np.nan if desired
  df['Precipitation Melted (mm)'] = df['Precipitation Melted (mm)'].astype('float64')
  
  # Fill in simplistic averages (mean of high/low) of temp and pressure where missing
  df['Temperature Average (C)'] = df['Temperature Average (C)'].fillna( (df['Temperature High (C)'] + df['Temperature Low (C)'])/2)
  df['Pressure Average (mbar)'] = df['Pressure Average (mbar)'].fillna( (df['Pressure High (mbar)'] + df['Pressure Low (mbar)'])/2)
  
  # Remove low pressure values
  df['Pressure Average (mbar)'] = df['Pressure Average (mbar)'].where(df['Pressure Average (mbar)']>800)
  
  # Calculate monthly averages
  df_avg = df.resample('1MS').agg({
    'Temperature Average (C)' : ['mean', 'count'],
    'Pressure Average (mbar)' : ['mean', 'count'],
    'Precipitation Melted (mm)' : ['mean', 'sum', 'count'],
    'Sea Surface Temperature (C)' : ['mean', 'count'],
    'Wind Average (knots)' : ['mean', 'count'],
  })
  
  # Save to CSV
  df_avg.to_csv(args.fname, float_format='%2.2f', header=[
    'Mean Temperature (C)','Temperature Count',
    'Mean Pressure (mbar)','Pressure Count',
    'Mean Precipitation (mm)','Sum Precipitation (mm)','Precipitation Count',
    'Mean Sea Surface Temperature (C)', 'Sea Surface Temperature Count',
    'Mean Windspeed (knots)', 'Windspeed Count'])
  print('Output file: %s' %args.fname)
